# Generated by Django 4.2.18 on 2025-01-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
    ]
