# Generated by Django 4.2.18 on 2025-01-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_remove_order_id_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
