# Generated by Django 4.2.18 on 2025-02-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_alter_order_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='signature_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
