# Generated by Django 4.2.18 on 2025-01-23 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Nandhini', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='nandy@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
