# Generated by Django 4.2.18 on 2025-01-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uuid',
        ),
    ]
