# Generated by Django 4.2.18 on 2025-01-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0008_otpdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_max_out',
        ),
    ]
