# Generated by Django 4.2.18 on 2025-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0009_remove_user_max_otp_try_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
