# Generated by Django 4.2.18 on 2025-02-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0022_subscriptionplan_alter_cartitems_cart_and_more'),
        ('otp_auth', '0012_alter_user_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storeapp.subscriptionplan'),
        ),
    ]
